name: TypeDoc

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.4.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Bootstrap Lerna
        run: yarn lerna bootstrap

      - name: Build packages
        run: yarn lerna run build

      - name: Generate TypeDoc for @gumhq/sdk
        run: yarn workspace @gumhq/sdk run build:docs

      - name: Generate TypeDoc for @gumhq/react-sdk
        run: yarn workspace @gumhq/react-sdk run build:docs

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./docs
